### ISSUE TITLE
Deprecation warning from Numpy

### ISSUE THREAD

**Issue by nigiord** [ibis-inria/wellFARE#5]
> [...]/wellFARE/wellfare/curves/Curve.py:431: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
>   x = self.x[max(0,i-l) : min(lx, i+r)] -  self.x[i]
> [...]/wellFARE/wellfare/curves/Curve.py:432: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
>   y = self.y[max(0,i-l) : min(lx, i+r)]
>[...]/lib/python3.5/site-packages/numpy/lib/polynomial.py:588: RuntimeWarning: invalid value encountered in true_divide
>   lhs /= scale
>[...]/lib/python3.5/site-packages/numpy/core/numeric.py:190: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
>   a = empty(shape, dtype, order)

Something to take care of at one point.

**Comment by yannickmartin** [comment]
Solved by applying int() for array indices.
